pub(crate) const COMMANDS: [(&str, &str); 18] = [
    ("help", "Show every command"),
    ("new", "Start a fresh session"),
    ("resume", "Reopen a saved session in this workspace"),
    ("role", "Choose Orchestrator, Writer, or Researcher"),
    ("model", "Discover or enter a model"),
    ("provider", "Edit provider settings"),
    ("attach", "Attach an image from the workspace"),
    ("theme", "Switch UI theme"),
    ("skills", "Browse and toggle discovered skills"),
    ("mcp", "Browse, toggle, or add MCP servers"),
    ("compact", "Summarise older turns to free context"),
    ("sidebar", "Toggle telemetry right sidebar"),
    ("reasoning", "Show or hide reasoning"),
    ("tools", "Expand or collapse tool output"),
    ("status", "Show runtime summary"),
    ("clear", "Clear the visible transcript"),
    ("stop", "Interrupt the current turn"),
    ("quit", "Leave enowx-cli"),
];
